# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03aa3cb8c37e2f3ab60db7f9c7bd77bcc58f76f9597d8b2326bf5183442d704513d5b38e32f1e458bd27a42abd65db2915fac8d34ef4414c5fdfa6cb0110bd7b

test:
  secret_key_base: d7ef7c6f568359183a71ab2663bf0cc6533cd5bd55d89996cfaeb88a05e8ce13ce5a8e3b0ed32a4d236512f8fb66a3afa474ed100cadb41388dab2258d431b4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
